export const $ = (id) => document.getElementById(id);

export const authScreen = $('auth-screen');
export const appScreen = $('app-screen');
export const authForm = $('auth-form');
export const authSubmit = $('auth-submit');
export const authStatus = $('auth-status');
export const passwordInput = $('password');
export const confirmField = $('confirm-field');
export const passwordConfirmInput = $('password-confirm');
export const accessTokenInput = $('access-token');
export const saltInput = $('salt');

export const depositSlot = $('deposit-slot');
export const chooseFilesBtn = $('choose-files-btn');
export const fileInput = $('file-input');
export const uploadQueue = $('upload-queue');
export const boxGrid = $('box-grid');
export const fileListEl = $('file-list');
export const fileListBody = $('file-list-body');
export const viewGridBtn = $('view-grid-btn');
export const viewListBtn = $('view-list-btn');
export const emptyState = $('empty-state');
export const gridLabel = $('grid-label');
export const searchInput = $('search-input');
export const searchClearBtn = $('search-clear');
export const gridSentinel = $('grid-sentinel');
export const usagePill = $('usage-pill');
export const vaultFingerprint = $('vault-fingerprint');
export const logoutBtn = $('logout-btn');
export const tokenBtn = $('token-btn');
export const saltBtn = $('salt-btn');
export const duressBtn = $('duress-btn');
export const lightbox = $('lightbox');
export const toasts = $('toasts');