export function $<T extends HTMLElement = HTMLElement>(id: string): T {
  const el = document.getElementById(id);
  if (!el) throw new Error(`Missing required element #${id}`);
  return el as T;
}

export const authScreen = $<HTMLDivElement>('auth-screen');
export const appScreen = $<HTMLDivElement>('app-screen');
export const authHeading = $<HTMLHeadingElement>('auth-heading');
export const authForm = $<HTMLFormElement>('auth-form');
export const authSubmit = $<HTMLButtonElement>('auth-submit');
export const authStatus = $<HTMLDivElement>('auth-status');
export const passwordInput = $<HTMLInputElement>('password');
export const confirmField = $<HTMLDivElement>('confirm-field');
export const passwordConfirmInput = $<HTMLInputElement>('password-confirm');
export const accessTokenInput = $<HTMLInputElement>('access-token');
export const serverUrlField = $<HTMLDivElement>('server-url-field');
export const serverUrlInput = $<HTMLInputElement>('server-url');

export const depositSlot = $<HTMLDivElement>('deposit-slot');
export const chooseFilesBtn = $<HTMLButtonElement>('choose-files-btn');
export const newFolderBtn = $<HTMLButtonElement>('new-folder-btn');
export const newTextFileBtn = $<HTMLButtonElement>('new-text-file-btn');
export const fileInput = $<HTMLInputElement>('file-input');
export const uploadQueue = $<HTMLDivElement>('upload-queue');
export const breadcrumbEl = $<HTMLDivElement>('breadcrumb');
export const boxGrid = $<HTMLDivElement>('box-grid');
export const fileListEl = $<HTMLDivElement>('file-list');
export const fileListBody = $<HTMLDivElement>('file-list-body');
export const viewGridBtn = $<HTMLButtonElement>('view-grid-btn');
export const viewListBtn = $<HTMLButtonElement>('view-list-btn');
export const selectToggleBtn = $<HTMLButtonElement>('select-toggle-btn');
export const selectionBarEl = $<HTMLDivElement>('selection-bar');
export const selectionCountEl = $<HTMLSpanElement>('selection-count');
export const selectionSelectAllBtn = $<HTMLButtonElement>('selection-select-all');
export const selectionDownloadBtn = $<HTMLButtonElement>('selection-download-btn');
export const selectionMoveBtn = $<HTMLButtonElement>('selection-move-btn');
export const selectionDeleteBtn = $<HTMLButtonElement>('selection-delete-btn');
export const selectionCancelBtn = $<HTMLButtonElement>('selection-cancel-btn');
export const emptyState = $<HTMLDivElement>('empty-state');
export const gridLabel = $<HTMLParagraphElement>('grid-label');
export const searchInput = $<HTMLInputElement>('search-input');
export const searchClearBtn = $<HTMLButtonElement>('search-clear');
export const gridSentinel = $<HTMLDivElement>('grid-sentinel');
export const usagePill = $<HTMLSpanElement>('usage-pill');
export const logoutBtn = $<HTMLButtonElement>('logout-btn');
export const tokenBtn = $<HTMLButtonElement>('token-btn');
export const passwordBtn = $<HTMLButtonElement>('password-btn');
export const themeBtn = $<HTMLButtonElement>('theme-btn');
export const duressBtn = $<HTMLButtonElement>('duress-btn');
export const sourceBtn = $<HTMLButtonElement>('source-btn');
export const settingsBtn = $<HTMLButtonElement>('settings-btn');
export const settingsMenu = $<HTMLDivElement>('settings-menu');
export const lightbox = $<HTMLDivElement>('lightbox');
export const toasts = $<HTMLDivElement>('toasts');